BASE_API_URL = "http://127.0.0.1:3000/apisig"
PESSOA_ID_PESSOA_URL = "#{BASE_API_URL}/pessoa/id_pessoa"
PESSOA_CPF_URL = "#{BASE_API_URL}/pessoa/cpf"
MODALIDADE_EDUCACAO_ID_MODALIDADE_EDUCACAO_URL = "#{BASE_API_URL}/modalidade_educacao/id_modalidade_educacao"
MODALIDADE_EDUCACAO_GET_ALL_URL = "#{BASE_API_URL}/modalidade_educacao"
RH_ID_SERVIDOR_URL = "#{BASE_API_URL}/servidor/id_servidor"
RH_ID_PESSOA_URL = "#{BASE_API_URL}/servidor/id_pessoa"