# /apisig/componente_curso_lato/id_componente_curso_lato/:id_componente_curso_lato
# /apisig/componente_curso_lato/id_componente_curricular/:id_componente_curricular
# /apisig/componente_curso_lato/id_curso_lato/:id_curso_lato
# /apisig/curso_lato/id_tipo_curso_lato/:id_tipo_curso_lato
# /apisig/curso_lato/id_curso/:id_curso
# /apisig/curso_lato/id_modalidade_educacao/:id_modalidade_educacao
# /apisig/curso_servidor/id_curso/:id_curso
# /apisig/curso_servidor/id_servidor/:id_servidor
# /apisig/curso_servidor/id_curso_servidor/:id_curso_servidor
# /apisig/curso_servidor/id_docente_externo/:id_docente_externo
# /apisig/discente_lato/id_discente/:id_discente
# /apisig/equipe_lato/id_equipe_lato/:id_equipe_lato
# /apisig/equipe_lato/id_servidor/:id_servidor
# /apisig/equipe_lato/id_docente_externo/:id_docente_externo
# /apisig/equipe_lato/id_disciplina/:id_disciplina
# /apisig/tipo_curso_lato/id_tipo_curso_lato/:id_tipo_curso_lato
# /apisig/turma_entrada_lato/id_turma_entrada/:id_turma_entrada